name: Frontend Quality Checks

on:
  # pull_request:
  #   # branches: [ main, master, develop ]
  #   paths:
  #     - 'resources/**'
  #     - 'package.json'
  #     - 'yarn.lock'
  #     - 'tsconfig.json'
  #     - 'vite.config.js'
  #     - 'svelte.config.js'
  #   paths-ignore:
  #     - 'public/**'
  #     - '/*'
  #     - '\.*'
  #     - '.github/**'
  #     - '.devcontainer/**'
  #     - '.vscode/**'

  workflow_call:
    inputs:
      node_version:
        description: 'NodeJS version to use'
        required: false
        default: '22'
        type: string

jobs:
  frontend-quality:
    runs-on: ubuntu-latest
    name: Frontend Linting & Type Checking
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile 

    - name: Run ESLint
      run: yarn run lint

    - name: Check code formatting
      run: yarn run format:check

    - name: Run TypeScript checks
      run: yarn run svelte:check
      continue-on-error: true  # Allow TypeScript errors but still report them

    - name: Run Vitest tests
      run: yarn run test:run

    - name: Build application
      run: yarn run build

    # - name: Upload build artifacts
    #   uses: actions/upload-artifact@v4
    #   if: always()
    #   with:
    #     name: frontend-build
    #     path: public/build/
    #     retention-days: 7